use_frameworks!

platform :ios, '8.0'

target 'NSCateStringSubKit_Example' do
  pod 'NSCateStringSubKit', :path => '../'

  target 'NSCateStringSubKit_Tests' do
    inherit! :search_paths

    
  end
end
